### ISSUE TITLE
Nativefier build fails in Docker

### ISSUE THREAD

**Issue by jrseliga** [jiahaog/nativefier#544]
### Description
Permission denied on nativefier build.

### Steps to reproduce issue
Follow Docker instructions in `README`

### Details
- [x] Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- [x] Full nativefier command used to build your app: `<command here>`
```
mkdir packages
docker run -v packages:/target local/nativefier https://github.com /target/
```
- [ ] Version of Nativefier (run `nativefier --version`): `v0.0.0`
- [ ] Version of node.js (run `node --version`): `v0.0.0`
- [x] OS: `<OS here>`
 - Ubuntu 17.10

- Same error in docker:latest container in Gitlab CI
```
image: docker:latest

services:
  - docker:dind

before_script:
  - docker build -t local/nativefier .

build-master:
  stage: build
  script:
    - mkdir - /tmp/nativifier
    - docker run -v /tmp/nativifier:/packaged local/nativefier https://github.com/ /packaged/
  only:
    - master
  artifacts:
    paths:
    - /tmp/nativifier
```
- [x] Error message / stack trace (if any):

```
{ Error: EACCES: permission denied, mkdir '/packaged/linux-x64-template'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/packaged/linux-x64-template' }
```
