### ISSUE TITLE
CSS not injected

### ISSUE THREAD

**Issue by Kore-Development** [jiahaog/nativefier#794]
### Description

I tried run the command `nativefier "https://www.discordapp.com/activity" --inject /Users/[REMOVED]/nox.css ~/Desktop` on macOS Majave and the css doesn't even load (from what I know). The css works with [userstyles.org](http://userstyles.org) just not Nativefier. Is there something I'm doing wrong?

The CSS
```css
@import url('https://cdn.jsdelivr.net/gh/rauenzi/Nox@master/release/import.css');

[class^="downloadAppButton"],[class^="guildSeparator"] {
    display: none !important;
}
```

### Steps to reproduce issue
Run the command and have the css file.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? I looked.
- Full nativefier command used to build your app: `nativefier "https://www.discordapp.com/activity" --inject /Users/[REMOVED]/nox.css ~/Desktop`
- Version of Nativefier (run `nativefier --version`): `7.6.12`
- Version of node.js (run `node --version`): `10.12.0`
- OS: `macOS Mojave`
- Error message / stack trace (if any): None
